name: Publish to NPM

on:
  release:
    types: [published]

jobs:
  Release:
    runs-on: ubuntu-latest
    if: github.actor == "marcus-j-davies"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
          registry-url: https://registry.npmjs.org/
      - run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
